# Assignment Day 15

In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [2]:
randomm = np.random.rand(3,3,3)
print(randomm)

[[[0.95193494 0.68948634 0.76483984]
  [0.14050389 0.76319882 0.45230076]
  [0.79885682 0.86530752 0.53221206]]

 [[0.14491426 0.18020097 0.99783192]
  [0.81186202 0.54029938 0.45442375]
  [0.98812158 0.5784317  0.08522539]]

 [[0.59194072 0.41939301 0.25394592]
  [0.60983786 0.66001217 0.84155255]
  [0.78966218 0.30936519 0.81945124]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
ran = np.diag(np.arange(4) + 1, k = -1)

print(ran)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [18]:
ran = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(ran)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [20]:
ran = np.random.random((5,5))
ran = (ran - np.mean (ran)) / (np.std (ran))
ran

array([[ 0.55395629, -0.96006238,  1.21223682, -0.30079721,  0.2860502 ],
       [ 0.6414718 , -0.33966994, -0.13484072,  0.04820679,  1.22296495],
       [-1.07237974,  1.06935304, -1.3496223 ,  0.06812343,  0.70543062],
       [ 1.57697296, -0.51647694, -1.3918106 , -0.09003726,  1.51372873],
       [ 1.56108397, -1.45074132, -1.45122809, -1.35238778, -0.04952529]])

# 5.  How to find common values between two arrays?

In [21]:
ran1 = np.random.randint(0,10,10)
ran2 = np.random.randint(0,10,10)

np.intersect1d(ran1, ran2)

array([0, 1, 3, 7])

# 6.How to get the dates of yesterday, today and tomorrow?

In [22]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("yesterday date :",yesterday)
print("Today date : " ,yesterday)
print("Tomorrow date : ",yesterday)

yesterday date : 2020-07-25
Today date :  2020-07-25
Tomorrow date :  2020-07-25


# 7. Consider two random array A and B, check if they are equal

In [25]:
ran1 = np.random.rand(4,4)
ran2 = np.random.rand(2,2)

equal = np.array_equal(ran1,ran2)
print(f'Array1:\n{ran1}\n')
print(f'Array2:\n{ran2}\n')
print(f'Equality: {equal}')

Array1:
[[0.54408104 0.98701399 0.78820237 0.93025225]
 [0.38874911 0.27959065 0.43423859 0.69321585]
 [0.91590793 0.03684664 0.77044566 0.60116248]
 [0.96579257 0.14306402 0.83908758 0.75458834]]

Array2:
[[0.40211529 0.01877051]
 [0.19415885 0.78586328]]

Equality: False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [26]:
ran = np.random.rand(10)
ran[ran.argmax()] = 0
print(ran)

[0.45420107 0.62315637 0.25501513 0.         0.11945371 0.59994214
 0.22915588 0.80260857 0.36626739 0.19084476]


# 9. How to print all the values of an array?

In [10]:
ran = np.ones((10, 10))
print(ran)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 10.Subtract the mean of each row of a matrix

In [28]:
ran = np.random.rand(3,3)
ran_mean = ran - ran.mean(axis=1, keepdims=True)

print(ran_mean)

[[ 0.27201754 -0.10580711 -0.16621043]
 [ 0.23663994 -0.07948713 -0.15715281]
 [ 0.37673254  0.05011581 -0.42684835]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [29]:
ran1 = np.ones(5)
ran2 = np.random.randint(0, len(ran1), 10)
ran1 += np.bincount(ran2, minlength = len(ran1))
ran1

array([5., 2., 2., 1., 5.])

# 12.How to get the diagonal of a dot product?

In [13]:

arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([ 0, 45, 29])

# 13.How to find the most frequent value in an array?

In [34]:

ran= np.random.randint(10,20,30)
print(ran)
max(set(ran), key = list(ran).count)

[17 15 15 11 12 12 18 15 13 18 19 10 14 19 10 18 12 10 13 15 17 14 17 13
 18 11 14 10 17 18]


18

# 14.How to get the n largest values of an array

In [35]:

ran = np.random.randint(20,30,100)
np.bincount(ran).argmax()

23

# 15.How to create a record array from a regular array?

In [40]:
a = np.array(['Happy','Learning','LetsUpgrade'])
b = np.array([23,55,110])
c = np.array(['u','r','l'])
records= np.core.records.fromarrays([a, b, c])
print(records[0])
print(records[1])
print(records[2])

('Happy', 23, 'u')
('Learning', 55, 'r')
('LetsUpgrade', 110, 'l')
